language: node_js
node_js: "6"
os:
- linux
- osx
- win32
dist: trusty
osx_image: xcode8.3
sudo: false

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron

addons:
  apt:
    packages:
    - fakeroot
    - rpm

branches:
  only:
  - master

install:
- npm install
- npm update
- npm install -g electron-forge

script:
- cd WingGcodeGenerator/src/main/electron/winggcode
- npm install serialport
- npm install electron-compile
- electron-forge make
- ls out

deploy:
  provider: pages
  skip_cleanup: true
  keep-history: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: WingGcodeGenerator/src/main/electron/winggcode/out
  on:
    branch: master