language: node_js
node_js: "6"
os:
- linux
#- osx
dist: trusty
osx_image: xcode8.3
sudo: false

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron

addons:
  apt:
    packages:
    - fakeroot
    - rpm

branches:
  only:
  - master

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install wine mono-devel -y
  
install:
- npm install
- npm update
- npm install -g electron-forge

script:
- cd WingGcodeGenerator/src/main/electron/winggcode
- npm install
- electron-forge make --platform=linux
- electron-forge make --platform=darwin
- electron-forge make --platform=win32
- pwd
- ls out
- ls out/*
- find out *.zip

deploy:
  provider: pages
  skip_cleanup: true
  keep-history: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: WingGcodeGenerator/src/main/electron/winggcode/out
  on:
    branch: master